__package_name__ = str(__package__)

try:
    # Generated by hatch-vcs at install/build time from git tags (git-ignored).
    from ._version import __version__
except ImportError:
    # Not built yet: fall back to the installed package metadata.
    from importlib.metadata import PackageNotFoundError, version

    try:
        __version__ = version(__package_name__)
    except PackageNotFoundError:
        __version__ = "0.0.0"

__all__ = ["__package_name__", "__version__"]
