"""Synthetic parser differential cases supplied by PR #142 review."""

DIFFERENTIAL_CASES: list[str] = []
LB = ["\x85", "\u2028", "\u2029"]
for lb in LB:
    DIFFERENTIAL_CASES += [
        f"a: x{lb}y\n",
        f"a: 'x{lb}y'\n",
        f'a: "x{lb}y"\n',
        f"a: |\n  x{lb}y\n",
        f"a: >\n  x{lb}y\n",
        f"a{lb}: 1\n",
        f"a: 1{lb}b: 2\n",
    ]
for esc in [
    "\\/",
    "\\N",
    "\\_",
    "\\L",
    "\\P",
    "\\x41",
    "\\u00e9",
    "\\U0001F600",
    "\\e",
    "\\0",
    "\\a",
    "\\ ",
    "\\t",
    "\\\t",
    "\\v",
    "\\b",
    "\\f",
    "\\r",
    '\\"',
    "\\\\",
    "\\\n  b",
    "\\q",
    "\\x4",
    "\\uD800",
]:
    DIFFERENTIAL_CASES.append(f'a: "x{esc}y"\n')
DIFFERENTIAL_CASES += [
    "a:\tb\n",
    "a: b\t\n",
    "a: \tb\n",
    "- \tx\n",
    "a:\n\t- 1\n",
    "a: |\n  x\ty\n",
    "a: |\n\tx\n",
    "a: 'x\ty'\n",
    'a: "x\ty"\n',
    "\ta: 1\n",
    "a: 1 \t# c\n",
    "a:\n  b: 1\n\t\n",
    "a: [1,\t2]\n",
    "{a:\t1}\n",
]
DIFFERENTIAL_CASES += [
    "\ufeffa: 1\n",
    "a: 1\n\ufeffb: 2\n",
    "a: x\ufeffy\n",
    "\ufeff\ufeffa: 1\n",
    "---\n\ufeffa: 1\n",
]
DIFFERENTIAL_CASES += [
    "{a: 1, b: [1,2]}\n",
    "{a:1}\n",
    "[a:1]\n",
    "{a, b}\n",
    "{? a : b}\n",
    "[a: b]\n",
    '{"a":1}\n',
    "{a: b, }\n",
    "[a, ]\n",
    "[a: b, c: d]\n",
    "{a: {b: [c, {d: e}]}}\n",
    "[? a : b]\n",
    "{a: }\n",
    "{: a}\n",
    "[ , ]\n",
    "{a: b c}\n",
    "{a: b\n c}\n",
    "[a\n b]\n",
    "{'a':1}\n",
    "{a: -1}\n",
    "[-1, - 1]\n",
    "{a: [}\n",
    "a: {b: 1}c\n",
    "[a]b\n",
    "{a: 'x'y}\n",
    "a: [1, 2]\n# c\n",
    "[a, b]: c\n",
    "{a: 1}: x\n",
    "? - a\n: b\n",
    "? a\n: b\n",
    "? a\n",
    ": a\n",
]
DIFFERENTIAL_CASES += [
    "a: b: c\n",
    "a: -1\n",
    "a: - b\n",
    "a: #x\n",
    "a: b #c\n",
    "a: b#c\n",
    "a:b\n",
    "a :1\n",
    "a : 1\n",
    "'a' : 1\n",
    "a: b\n  c\n",
    "a: b\nc\n",
    "- a\n- b: c\n  d: e\n",
    "a:\n- 1\n- 2\n",
    "- - 1\n  - 2\n",
    "a: - 1\n",
    "a: x\n  - y\n",
    "-\n",
    "- \n",
    "-x\n",
    "a: ---\n",
    "a: ...\n",
    "--- a\n",
    "... \n",
    "a: '---'\n",
    "a: !\n",
    "a: '\n'\n",
]
DIFFERENTIAL_CASES += [
    "k" * 1030 + ": v\n",
    "'" + "k" * 1030 + "': v\n",
    "? " + "k" * 1030 + "\n: v\n",
    "a: " + "v" * 5000 + "\n",
]
for s in [
    "0x1F",
    "0o17",
    "0b101",
    "0_1",
    "1_000",
    "+1",
    "-0",
    "012",
    "0o",
    "0x",
    "1.",
    ".5",
    "1e3",
    "1E3",
    "1.0e+3",
    "+.inf",
    "-.inf",
    ".NaN",
    ".nan",
    "1__0",
    "0x_1",
    "08",
    "09",
    "0.",
    "-.5",
    "1:20",
    "190:20:30",
    "2024-01-01",
    "2024-01-01T00:00:00Z",
    "TRUE",
    "True",
    "tRUE",
    "Null",
    "NULL",
    "nULL",
    "~",
    "y",
    "n",
    "yes",
    "No",
    "on",
    "OFF",
    "0777",
    "0o777",
    "-0x1",
    "+0o7",
    "0B1",
    "0X1F",
    "1e",
    "e3",
    "1.5e3",
    "1_0.5",
    ".1_0",
    "123456789012345678901234567890",
    "1e400",
    "-1e400",
    "0.0",
    "-0.0",
    "+0",
    "00",
    "0e0",
    "1E+03",
    "1.e3",
    "+.5",
    "._5",
    ".",
    "+",
    "-",
    "+-1",
    "--1",
    "0x-1",
    "1 000",
    "１２",
    "٣",
    "nan",
    "inf",
    "-inf",
    ".Inf",
    ".INF",
    "0xG",
    "0o8",
    "0b2",
    "1_",
    "_1",
    "+_1",
    "0x1_F",
    "0o1_7",
    "0b1_0",
    "1.0_0e1_0",
    "true_",
    "falsey",
    "null0",
    "~a",
]:
    DIFFERENTIAL_CASES += [f"a: {s}\n", f"{s}: v\n", f"- {s}\n"]
DIFFERENTIAL_CASES += [
    "a: |\n  x\n\n",
    "a: |-\n  x\n\n",
    "a: |+\n  x\n\n",
    "a: |2\n   x\n",
    "a: >\n  x\n  y\n\n  z\n",
    "a: >\n  x\n    y\n  z\n",
    "a: >-\n  x\n",
    "a: >+\n  x\n\n\n",
    "a: |\n\n  x\n",
    "a: |\n  \n  x\n",
    "a: >\n\n  x\n   y\n",
    "a: |1\n  x\n",
    "a: |9\n  x\n",
    "a: |\nx\n",
    "a: |  # c\n  x\n",
    "a: >2-\n   x\n",
    "a: |-2\n   x\n",
    "a: |\n  x\n b: 1\n",
    "a: >\n  x\n\n  \n  y\n",
    "a: |\n   x\n  y\n",
]
DIFFERENTIAL_CASES += [
    "a: x\n  y\n\n  z\n",
    "a: 'x\n  y\n\n  z'\n",
    'a: "x\n  y\n\n  z"\n',
    "a: 'it''s'\n",
    'a: "x\\\n  y"\n',
    "a: 'x  \n  y'\n",
    'a: "x  \n  y"\n',
    "a: x  \n  y\n",
    "a: 'x\n\n\n  y'\n",
]
DIFFERENTIAL_CASES += [
    "---\na: 1\n...\n",
    "a: 1\n---\n",
    "a: 1\n---\nb: 2\n",
    "--- !tag\na: 1\n",
    "%TAG ! tag:x,2000:\n---\na: 1\n",
    "%YAML 1.2\n%YAML 1.2\n---\na: 1\n",
    "%YAML 1.1\n---\na: 1\n",
    "%YAML 1.3\n---\na: 1\n",
    "%YAML 2.0\n---\na: 1\n",
    "%FOO bar\n---\na: 1\n",
    "%YAML 1.2\na: 1\n",
    "%YAML 1.2\n---\na: 1\n...\n%YAML 1.2\n---\nb: 1\n",
    "",
    "# c\n",
    "---\n",
    "--- \n...\n",
    "null\n",
    "...\n",
    "---\n...\n---\n",
    "\n\n",
    "a: 1\n...\n",
    "a: 1\n...\n# c\n",
    "a: 1\n... # c\n",
    "%YAML 1.2 # c\n---\na: 1\n",
    "%YAML  1.2\n---\na: 1\n",
    "%YAML 1.02\n---\na: 1\n",
    "%YAML 01.2\n---\na: 1\n",
]
DIFFERENTIAL_CASES += [
    "a: !!str 1\n",
    "a: ! 1\n",
    "&a a: 1\n",
    "a: &x 1\nb: *x\n",
    "a: !<tag:yaml.org,2002:str> 1\n",
    "!!map {a: 1}\n",
    "a: !local x\n",
]
DIFFERENTIAL_CASES += [
    'a: "\x01"\n',
    "a: '\x7f'\n",
    "a: x\x7fy\n",
    'a: "\x7f"\n',
    "a: \x00\n",
    "a: '\x1b'\n",
    'a: "\x9f"\n',
    "a: \x85\n",
    "a: \ue000\n",
    "a: \ufffe\n",
    "a: 😀\n",
    "a: é\n",
    "a: \u200b\n",
    "a: '\ud7ff'\n",
]
DIFFERENTIAL_CASES += [
    "<<: {a: 1}\n",
    '"<<": 1\n',
    "'<<': 1\n",
    "a: 1\na: 2\n",
    "a: 1\n'a': 2\n",
    "{a: 1, a: 2}\n",
    'a: 1\n"a": 2\n',
    "1: a\n'1': b\n",
    "a:\n  b: 1\n  b: 2\n",
    "- {a: 1, a: 1}\n",
]
DIFFERENTIAL_CASES += [
    "a: 1\r\nb: 2\r\n",
    "a: 1\rb: 2\r",
    "a: |\r\n  x\r\n  y\r\n",
    "a: 'x\r\n  y'\n",
    "a: 1\r\n\r\n",
]
